### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by romosch** [gleisonsdm/TaskMiner#1]
During the 5th step of the installation during the `make ${MAKEFLAG}` instruction I get the following error:

`fatal error: clang/Driver/Options.inc: No such file or directory #include "clang/Driver/Options.inc"`

Any ideas? Is there a specific version of cmake that I should be using?

**Comment by gleisonsdm** [comment]
HI Nicolas,

I think it's relative the installation of our scope finder, I will check it. Can you send me more details? I would like to reproduce the bug.

Regards,

   Gleison
