### ISSUE TITLE
Errors in run.sh

### ISSUE THREAD

**Issue by romosch** [gleisonsdm/TaskMiner#2]

**Comment by romosch** [comment]
Running the run.sh script gives the following error:
`opt: Too many positional arguments specified!`

result.bc gets created, but not result2.bc.

**Comment by gleisonsdm** [comment]
Hi Nicolas,

I am sorry about that, the script needs the optional flags (I need to insert the code to make them optional). I fixed this and now seems it is working well. Can you update your local files and give me a feedback?

Regards,

    Gleison

**Comment by romosch** [comment]
Yup, that did the trick
